# Generated by Django 5.2.10 on 2026-01-21 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_account_deletion_fields'),
        ('chatbot', '0004_add_performance_indexes'),
    ]

    operations = [
    ]
