# Generated by Django 5.2.10 on 2026-01-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_fix_sentiment_score'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='msg_sent_label_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='sentimentreport',
            name='report_user_time_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentreport',
            name='average_score',
            field=models.FloatField(),
        ),
    ]
