# Generated by Django 5.2.10 on 2026-01-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_remove_message_msg_sent_label_time_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE sentiment_reports DROP COLUMN mood_score;",
            reverse_sql="ALTER TABLE sentiment_reports ADD COLUMN mood_score FLOAT;",
        ),
    ]
