# Generated by Django 5.2.10 on 2026-02-03 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_doctorprofile_doctorappointment_doctor_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoreticalFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('principles', models.JSONField(default=dict, help_text='Core theoretical principles')),
                ('mechanisms', models.JSONField(default=list, help_text='How the intervention works')),
                ('hypotheses', models.JSONField(default=list, help_text='Testable hypotheses')),
                ('evidence_base', models.TextField(help_text='Research citations and evidence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'theoretical_frameworks',
            },
        ),
        migrations.RemoveField(
            model_name='doctorappointment',
            name='doctor_email',
        ),
        migrations.RemoveField(
            model_name='doctorappointment',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='doctorappointment',
            name='reminder_sent',
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorappointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='scheduled', max_length=20),
        ),
        migrations.CreateModel(
            name='CBTBehavioralActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('activity_description', models.TextField()),
                ('activity_type', models.CharField(choices=[('pleasure', 'Pleasure Activity'), ('mastery', 'Mastery Activity'), ('social', 'Social Activity'), ('physical', 'Physical Activity'), ('self_care', 'Self-Care')], max_length=50)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('predicted_pleasure', models.IntegerField(help_text='Expected enjoyment (0-10)')),
                ('predicted_mastery', models.IntegerField(help_text='Expected sense of accomplishment (0-10)')),
                ('actual_pleasure', models.IntegerField(blank=True, help_text='Actual enjoyment (0-10)', null=True)),
                ('actual_mastery', models.IntegerField(blank=True, help_text='Actual accomplishment (0-10)', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('autonomy_support', models.BooleanField(default=True, help_text='User chose this activity')),
                ('competence_building', models.BooleanField(default=False, help_text='Builds skills/confidence')),
                ('relatedness_fostering', models.BooleanField(default=False, help_text='Involves social connection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_activations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbt_behavioral_activation',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='CBTExposureHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fear_target', models.CharField(help_text='What anxiety/fear are we addressing?', max_length=200)),
                ('hierarchy_items', models.JSONField(default=list, help_text='List of exposure steps with SUDS ratings')),
                ('current_step', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_exposure_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposure_hierarchies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbt_exposure_hierarchy',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CBTThoughtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.TextField(help_text='What was happening? Where? When? With whom?')),
                ('automatic_thoughts', models.TextField(help_text='What thoughts went through your mind?')),
                ('emotions', models.JSONField(default=dict, help_text='What emotions did you feel? Rate intensity 0-100')),
                ('distortions', models.JSONField(default=list, help_text='Types of thinking errors')),
                ('evidence_for', models.TextField(blank=True, help_text='Evidence that supports the thought')),
                ('evidence_against', models.TextField(blank=True, help_text='Evidence that contradicts the thought')),
                ('alternative_thought', models.TextField(blank=True, help_text='More balanced perspective')),
                ('emotions_after', models.JSONField(default=dict, help_text='Emotions after reframing (0-100)')),
                ('behavioral_response', models.TextField(blank=True, help_text='What action did you take?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thought_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cbt_thought_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GAD7Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('baseline', 'Baseline'), ('follow_up', 'Follow-up'), ('weekly', 'Weekly Check-in'), ('crisis', 'Crisis Assessment')], default='baseline', max_length=20)),
                ('q1_nervous', models.IntegerField(help_text='Feeling nervous, anxious, or on edge')),
                ('q2_control', models.IntegerField(help_text='Not being able to stop or control worrying')),
                ('q3_worrying', models.IntegerField(help_text='Worrying too much about different things')),
                ('q4_relaxing', models.IntegerField(help_text='Trouble relaxing')),
                ('q5_restless', models.IntegerField(help_text="Being so restless that it's hard to sit still")),
                ('q6_irritable', models.IntegerField(help_text='Becoming easily annoyed or irritable')),
                ('q7_afraid', models.IntegerField(help_text='Feeling afraid as if something awful might happen')),
                ('total_score', models.IntegerField(help_text='Sum of all items (0-21)')),
                ('severity', models.CharField(choices=[('minimal', 'Minimal (0-4)'), ('mild', 'Mild (5-9)'), ('moderate', 'Moderate (10-14)'), ('severe', 'Severe (15-21)')], max_length=20)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('requires_intervention', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gad7_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gad7_assessments',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('cbt', 'Cognitive Behavioral Therapy'), ('behavioral_activation', 'Behavioral Activation'), ('exposure', 'Exposure Therapy'), ('thought_restructuring', 'Cognitive Restructuring'), ('combined', 'Combined Approach')], max_length=50)),
                ('baseline_phq9', models.IntegerField(blank=True, null=True)),
                ('baseline_gad7', models.IntegerField(blank=True, null=True)),
                ('baseline_date', models.DateTimeField()),
                ('followup_phq9', models.IntegerField(blank=True, null=True)),
                ('followup_gad7', models.IntegerField(blank=True, null=True)),
                ('followup_date', models.DateTimeField(blank=True, null=True)),
                ('phq9_change', models.FloatField(blank=True, help_text='Change in PHQ-9 score', null=True)),
                ('gad7_change', models.FloatField(blank=True, help_text='Change in GAD-7 score', null=True)),
                ('phq9_effect_size', models.FloatField(blank=True, null=True)),
                ('gad7_effect_size', models.FloatField(blank=True, null=True)),
                ('clinically_significant_change', models.BooleanField(default=False, help_text='>=50% symptom reduction')),
                ('sessions_completed', models.IntegerField(default=0)),
                ('thought_records_completed', models.IntegerField(default=0)),
                ('activities_completed', models.IntegerField(default=0)),
                ('autonomy_score', models.FloatField(blank=True, help_text='Perceived autonomy (1-7)', null=True)),
                ('competence_score', models.FloatField(blank=True, help_text='Perceived competence (1-7)', null=True)),
                ('relatedness_score', models.FloatField(blank=True, help_text='Perceived relatedness (1-7)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_outcomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intervention_outcomes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PHQ9Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(choices=[('baseline', 'Baseline'), ('follow_up', 'Follow-up'), ('weekly', 'Weekly Check-in'), ('crisis', 'Crisis Assessment')], default='baseline', max_length=20)),
                ('q1_interest', models.IntegerField(help_text='Little interest or pleasure in doing things')),
                ('q2_depressed', models.IntegerField(help_text='Feeling down, depressed, or hopeless')),
                ('q3_sleep', models.IntegerField(help_text='Trouble falling/staying asleep, or sleeping too much')),
                ('q4_fatigue', models.IntegerField(help_text='Feeling tired or having little energy')),
                ('q5_appetite', models.IntegerField(help_text='Poor appetite or overeating')),
                ('q6_failure', models.IntegerField(help_text='Feeling bad about yourself or that you are a failure')),
                ('q7_concentration', models.IntegerField(help_text='Trouble concentrating on things')),
                ('q8_psychomotor', models.IntegerField(help_text='Moving or speaking slowly or being fidgety/restless')),
                ('q9_suicidal', models.IntegerField(help_text='Thoughts of being better off dead or hurting yourself')),
                ('total_score', models.IntegerField(help_text='Sum of all items (0-27)')),
                ('severity', models.CharField(choices=[('minimal', 'Minimal (0-4)'), ('mild', 'Mild (5-9)'), ('moderate', 'Moderate (10-14)'), ('moderately_severe', 'Moderately Severe (15-19)'), ('severe', 'Severe (20-27)')], max_length=20)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('requires_intervention', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phq9_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'phq9_assessments',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.AddIndex(
            model_name='gad7assessment',
            index=models.Index(fields=['user', '-completed_at'], name='gad7_assess_user_id_fca4d5_idx'),
        ),
        migrations.AddIndex(
            model_name='gad7assessment',
            index=models.Index(fields=['severity'], name='gad7_assess_severit_131dcf_idx'),
        ),
        migrations.AddIndex(
            model_name='phq9assessment',
            index=models.Index(fields=['user', '-completed_at'], name='phq9_assess_user_id_0f279f_idx'),
        ),
        migrations.AddIndex(
            model_name='phq9assessment',
            index=models.Index(fields=['severity'], name='phq9_assess_severit_35e1c5_idx'),
        ),
    ]
