# Generated by Django 5.2.10 on 2026-02-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_add_semantic_analysis_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='cognitive_distortions',
            field=models.JSONField(blank=True, default=dict, help_text='CBT cognitive distortions'),
        ),
        migrations.AlterField(
            model_name='message',
            name='coping_indicators',
            field=models.JSONField(blank=True, default=list, help_text='Positive coping strategies'),
        ),
        migrations.AlterField(
            model_name='message',
            name='crisis_confidence',
            field=models.FloatField(blank=True, help_text='Crisis detection confidence', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='crisis_level',
            field=models.CharField(blank=True, help_text='Crisis urgency level', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='key_phrases',
            field=models.JSONField(blank=True, default=list, help_text='Key phrases extracted'),
        ),
        migrations.AlterField(
            model_name='message',
            name='linguistic_features',
            field=models.JSONField(blank=True, default=dict, help_text='Linguistic analysis data'),
        ),
        migrations.AlterField(
            model_name='message',
            name='semantic_similarity',
            field=models.FloatField(blank=True, help_text='Similarity with history', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='themes',
            field=models.JSONField(blank=True, default=dict, help_text='Mental health themes detected'),
        ),
    ]
